---
- name: Create the redis systemd unit file
  ansible.builtin.copy:
    src: container-redis.service
    dest: /etc/systemd/system/container-redis.service
    mode: '0644'
    owner: root
    group: root
  notify:
    - restart redis container
  register: redis_systemd_unit

- name: Enable and start the redis service
  ansible.builtin.systemd:
    name: container-redis.service
    state: started
    enabled: true
    daemon_reload: "{{ redis_systemd_unit is changed }}"

- name: Create a firewalld zone to handle incoming connections to redis
  ansible.posix.firewalld:
    zone: redis-access
    permanent: true
    state: present
  register: firewalld_zone_redis_access_result

- name: Reload firewalld if the zone was created
  command:
    cmd: firewall-cmd --reload
  when: firewalld_zone_redis_access_result.changed|default(false)

- name: Allow redis service for zone redis-access
  ansible.posix.firewalld:
    service: redis
    zone: redis-access
    state: enabled
    permanent: true
    immediate: true

- name: Allow required hosts to connect to redis
  ansible.posix.firewalld:
    source: "{{ hostvars[item].ansible_host }}/32"
    zone: redis-access
    state: enabled
    permanent: true
    immediate: true
  loop:
    "{{ groups['dci_feeder_worker'] | default([]) + groups['dci_api'] | default([]) }}"
