---
dci_api_container_image: quay.io/distributedci/dci-control-server:latest
dci_api_container_network: quadlet.network
dci_api_container_scale: 4
dci_api_container_spec:
  image: "{{ dci_api_container_image }}"
  no_quadlet_image: true
  network: "{{ dci_api_container_network }}"
  env_file: /etc/dci-api/dci-api.env
  health:
    cmd: curl --head http://localhost:5000/api/v1/
  scale: "{{ dci_api_container_scale }}"
  labels:
    io.distributed-ci.app: dci_api
  notify: true
  timeoutstartsec: 300

dci_api_auth_tracking_container_network: quadlet.network
dci_api_auth_tracking_container_spec:
  image: "{{ dci_api_container_image }}"
  no_quadlet_image: true
  network: "{{ dci_api_container_network }}"
  env_file: /etc/dci-api/dci-api.env
  labels:
    io.distributed-ci.app: dci_api_auth_tracking
  timeoutstartsec: 300
  entrypoint:
  command: bin/dci-sync-redis-auth --interval 30 --threshold 10

# If the role is deployed on multiple machines,
# this should be enabled on one machine only.
dci_api_auth_tracking_enabled: true

dci_redis_url: "redis://localhost:6379/0"

gunicorn_nb_workers: 1
gunicorn_worker_connections: 100
gunicorn_max_requests: 0
gunicorn_max_requests_jitter: 0
gunicorn_timeout: 30
gunicorn_graceful_timeout: 90
gunicorn_extra_cmd_args: ""

rhdl_api_url: "https://api.rhdl.distributed-ci.io/api/v1"
...
